### ISSUE TITLE
Model Compiling to Desired Directory

### ISSUE THREAD

**Issue by SethTooQuick** [bonjorno7/SourceOps#23]
To compile models to a directroy which doesn't have any native source files, the model should be copied / compiled to the directory set.

Maybe have a base game (CSGO), then have another game config (Custom Map Assets) use everything from the base game besides the model compiling directory.

**Comment by bonjorno7** [comment]
I'll add a checkbox that copies the compiled model to a folder next to your blend, and another checkbox to do the same for the model's materials. The folder structure will be the same as the game so that you can easily zip it and send it to people.

**Comment by bonjorno7** [comment]
This issue resulted in the "Additional Path" for games, so that's done I suppose
