### ISSUE TITLE
Difference between SourceOps and SourceIO?

### ISSUE THREAD

**Issue by 0Curtain0** [bonjorno7/SourceOps#26]
Hi, sometime in the future, I'm planning to do a guide on how to import SFM models into Blender. 
I want the readers to be able to know the strengths, weaknesses and purposes of each of the following tools: 
- **Blender Source Tools** + **Crowbar**
- **SourceIO**
- **SourceOps** 

I hope you don't mind describing these tools in the way you see them so that new Blender users will know what to expect with each tool. 

I usually post guides/tutorials [HERE](https://www.deviantart.com/xcurtainx/journal/) and [HERE](https://smutba.se/tutorials/). 

Thank you.

**Comment by bonjorno7** [comment]
SourceOps only does export, not import. As for SourceIO you'll have to ask @REDxEYE

**Comment by REDxEYE** [comment]
SourceIO is all about importing Source content
Where SourceOps is about exporting and compiling stuff

**Comment by 0Curtain0** [comment]
@bonjorno7 
@REDxEYE 
Thank you both, I will close this.
