### ISSUE TITLE
Bone name appends Armature's name

### ISSUE THREAD

**Issue by SupinePandora43** [bonjorno7/SourceOps#45]
[smd.py#L34](https://github.com/bonjorno7/SourceOps/blob/master/addon/types/model_export/smd.py#L34) :anger: 

it doesnt allow to use `weapon_bone`, because it become `Armature.weapon_bone`.

**Comment by bonjorno7** [comment]
Not a bug; please rename this issue to something more descriptive. I'll try to think of a way to make it behave like you want.
