### ISSUE TITLE
Support for Non Linear Animation

### ISSUE THREAD

**Issue by SupinePandora43** [bonjorno7/SourceOps#49]
![image](https://user-images.githubusercontent.com/36124472/87767771-93b21e80-c834-11ea-82f6-c4d5c8b5d8a9.png)
**`spin`** get exported
`fl_susp` will **not** get exported
`fr_susp` will **not** get exported
`rl_susp` will **not** get exported
`rr_susp` will **not** get exported

**Comment by SupinePandora43** [comment]
![image](https://user-images.githubusercontent.com/36124472/87769538-3b305080-c837-11ea-857e-9d602d18bba2.png)

**Comment by bonjorno7** [comment]
I have no idea how that stuff works, but if you put them all in the timeline they'll all be exported properly.

**Comment by SupinePandora43** [comment]
:confused:

**Comment by bonjorno7** [comment]
I now understand how to use actions and non-linear animation.
Rewriting the addon to use them is quite a task, so dunno when I'll have the time.

**Comment by bonjorno7** [comment]
Actions are supported now, though you have to manually add sequences and assign each an action (cause there's options like snap, loop, fps, etc).
