### ISSUE TITLE
blank bodygroup is forced

### ISSUE THREAD

**Issue by SupinePandora43** [bonjorno7/SourceOps#50]
https://github.com/bonjorno7/SourceOps/blob/ef4b81f947c922695a7ffba338ca4118dff697d9/addon/types/model_export/model.py#L174
it can't be disabled
![image](https://user-images.githubusercontent.com/36124472/88077835-2506f500-cb95-11ea-8a9d-166c7ea1a3dd.png)

**Comment by bonjorno7** [comment]
I guess I could just add a checkbox for it next to bodygroups

**Comment by SupinePandora43** [comment]
**OwO**

**Comment by SupinePandora43** [comment]
yeyeyyeyeyey i'm beck
