### ISSUE TITLE
Attachments support

### ISSUE THREAD

**Issue by SupinePandora43** [bonjorno7/SourceOps#55]
like attach empty object to bone, and export as attachment

**Comment by bonjorno7** [comment]
At the moment I'm too busy with work, but maybe in the christmas vacation I'll have time. I don't know how you attach an empty to a bone, so you'll have to show me.

**Comment by SupinePandora43** [comment]
> At the moment I'm too busy with work, but maybe in the christmas vacation I'll have time. I don't know how you attach an empty to a bone, so you'll have to show me.

:flushed: i don't know either

**Comment by REDxEYE** [comment]
![image](https://user-images.githubusercontent.com/17544576/102089196-f6800400-3e2c-11eb-9337-467d031b6730.png)
@bonjorno7

**Comment by REDxEYE** [comment]
You can parent empties to bones

**Comment by bonjorno7** [comment]
Oh, thanks.

**Comment by bonjorno7** [comment]
Done with #58 and #59

**Comment by SupinePandora43** [comment]
whoa
