### ISSUE TITLE
Support multiple texture group materials

### ISSUE THREAD

**Issue by SupinePandora43** [bonjorno7/SourceOps#56]
https://developer.valvesoftware.com/wiki/$texturegroup

**Comment by gusdleon** [comment]
SourceOps already supported that before this issue was created

Textures Tab>Skins list

**Comment by bonjorno7** [comment]
Oh I just figured out what you meant as well.
Yeah I should fix that some time.

**Comment by bonjorno7** [comment]
It's now a space separated list, just like VMT uses natively (it just copies the strings as-is now).

**Comment by gusdleon** [comment]
thanks, @bonjorno7 this is great.

so... I think this its the way it works now right?

![image](https://user-images.githubusercontent.com/3170940/128616950-d62658ce-e52f-4186-bc4f-696fe9046580.png)

**Comment by gusdleon** [comment]
Sorry, I didn't saw the tooltip haha
![image](https://user-images.githubusercontent.com/3170940/128616990-99015ffd-36bb-4a18-9e67-a118ffb3e705.png)

Thanks again :)
