### ISSUE TITLE
DMX Model support

### ISSUE THREAD

**Issue by SupinePandora43** [bonjorno7/SourceOps#61]
Kinda sus

**Comment by REDxEYE** [comment]
SourceOps has no support for writing DMX files use Blender Source Tools for that

**Comment by bonjorno7** [comment]
I don't think I'll write a DMX exporter ever, let alone soon; sorry.

**Comment by CabbageMcGravel** [comment]
From the above responses in the Issue, I think it makes sense to close this.

**Comment by SupinePandora43** [comment]
Who are you?

**Comment by CabbageMcGravel** [comment]
I am the ghost of GitHub past.
And a friend of bonjorno!

**Comment by bonjorno7** [comment]
I guess if there was an operator similar to the one used for FBX export, I could add support for it to SourceOps, maybe.
But yeah probably not, and I could always reopen later.
