### ISSUE TITLE
Error Installing in Linux

### ISSUE THREAD

**Issue by LoveRenamon** [bonjorno7/SourceOps#62]
Direct installing **`0.5.2.8`** or later versions on Linux cause issues with `import ctypes.wintypes`
![Screenshot from 2021-04-01 15-30-43](https://user-images.githubusercontent.com/9941414/113338305-4f51aa80-92ff-11eb-8206-1482ce81525e.png)

I used as workaround two options:
> First install the **`0.5.2.6`**, enable it, then upgrade to last version; Blender don't check this import after enabled;

or
> Just comment the addon `./addon/utils/common.py` line 5 then install normally.

**Comment by bonjorno7** [comment]
Whoops my bad, fixed now in release [0.5.3.4](https://github.com/bonjorno7/SourceOps/releases/tag/v0.5.3.4)
