### ISSUE TITLE
UI support for compiling models from FBX (CSGO)

### ISSUE THREAD

**Issue by 18swenskiq** [bonjorno7/SourceOps#64]
Currently to my knowledge, there is no simple button method for compiling a model from FBX for CSGO (for the purposes of having a 2nd UV), this would be an incredible feature and would to my knowledge make other methods of compiling models obsolete.

**Comment by bonjorno7** [comment]
You're right, I've been putting this off for far too long.
I made a first draft on the [fbx branch](https://github.com/bonjorno7/SourceOps/tree/fbx) just now.
It's still pretty rough around the edges but I think I'll manage.

**Comment by bonjorno7** [comment]
[Done.](https://github.com/bonjorno7/SourceOps/releases/tag/0.5.4)
