### ISSUE TITLE
cannot export vmf

### ISSUE THREAD

**Issue by Pop4484** [bonjorno7/SourceOps#77]
i try to port a roblox map to gmod but i get this error

Python: Traceback (most recent call last):
  File "C:\Users\Pop4484\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_valvesource\GUI.py", line 84, in draw
    row.label(text=GetCustomPropName(scene.vs,"export_format",":"))
  File "C:\Users\Pop4484\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_valvesource\utils.py", line 302, in GetCustomPropName
    return "".join([pgettext(typing.get_type_hints(type(data))[prop][1]['name']), suffix])
TypeError: '_PropertyDeferred' object is not subscriptable

location: <unknown location>:-1

**Comment by Pop4484** [comment]
when i load the vmf in hammer it says all brushes are invalid and deletes everything

**Comment by bonjorno7** [comment]
The error you sent me has nothing to do with SourceOps; it is happening the the UI code for Blender Source Tools.
I'm not surprised the brushes are invalid. Brushes have to follow specific rules (inherent to VMF), and geometry from other games won't follow those rules.
I can't change that, but I can try to help you on the discord: https://discord.gg/N35zhHm
